# [[plugins]]
# repo        = 'Shougo/deoplete.nvim'
# depends     = ['context_filetype.vim']
# on_i        = 1
# hook_add    = 'let g:deoplete#enable_at_startup = 1'
# hook_source = 'source $XDG_CONFIG_HOME/nvim/user_autoload/plugins/deoplete.rc.vim'


[[plugins]]
repo    = 'Shougo/neoinclude.vim'
on_ft   = ['c', 'cpp']


[[plugins]]
repo        = 'thinca/vim-quickrun'
on_ft       = ['tex']
on_map      = {n = '<Plug>'}
hook_add    = 'nmap <silent> <C-l> <Plug>(quickrun)'
hook_source = 'source $XDG_CONFIG_HOME/nvim/user_autoload/plugins/vim-quickrun.rc.vim'


[[plugins]]
repo        = 'kana/vim-smartchr'
depends     = 'context_filetype.vim'
on_event    = 'InsertCharPre'
hook_source = 'source $XDG_CONFIG_HOME/nvim/user_autoload/plugins/vim-smartchr.rc.vim'


[[plugins]]
repo     = 'scrooloose/nerdtree'
hook_add = '''
  " vim起動時にNERDTreeを自動で起動する
  autocmd VimEnter * NERDTree
  " Vim&NERDTree起動時にカーソルをファイル側に表示する
  autocmd VimEnter * call timer_start(0, { -> feedkeys("\<C-w>w") })
'''
hook_source = 'source $XDG_CONFIG_HOME/nvim/user_autoload/plugins/nerdtree.rc.vim'


[[plugins]]
repo     = 'mattn/emmet-vim'
on_ft    = ['html']
hook_add = '''
  " expand html tag
  let g:user_emmet_leader_key = ','
'''


[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
hook_post_source = 'source $XDG_CONFIG_HOME/nvim/user_autoload/plugins/lexima.rc.vim'

