# Requirement
[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo     = 'itchyny/lightline.vim'
hook_add = 'source $XDG_CONFIG_HOME/nvim/user_autoload/plugins/lightline.rc.vim'


[[plugins]]
repo     = 'tomasr/molokai'
hook_add = '''
  let g:rehash256 = 1
  colorscheme molokai
  highlight Normal ctermbg=none
'''


[[plugins]]
repo     = 'scrooloose/nerdcommenter'
hook_add = 'source $XDG_CONFIG_HOME/nvim/user_autoload/plugins/nerdcommenter.rc.vim'


[[plugins]]
repo = 'Shougo/context_filetype.vim'



[[plugins]]
repo = 'prabirshrestha/async.vim'


[[plugins]]
repo     = 'prabirshrestha/vim-lsp'
depends  = ['async.vim']
hook_add = 'source $XDG_CONFIG_HOME/nvim/user_autoload/plugins/vim-lsp.rc.vim'


[[plugins]]
repo     = 'prabirshrestha/asyncomplete.vim'
hook_add = 'source $XDG_CONFIG_HOME/nvim/user_autoload/plugins/asyncomplete.rc.vim'


[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'


[[plugins]]
repo     = 'prabirshrestha/asyncomplete-file.vim'
hook_add = 'source $XDG_CONFIG_HOME/nvim/user_autoload/plugins/asyncomplete-file.rc.vim'


[[plugins]]
repo     = 'prabirshrestha/asyncomplete-buffer.vim'
hook_add = 'source $XDG_CONFIG_HOME/nvim/user_autoload/plugins/asyncomplete-buffer.rc.vim'

