"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$fill\
$hostname\
$line_break$character
"""

palette = 'color'

[palettes.color]
# 背景色を限界まで暗く設定
bg_dark     = '#1d2021'  # OS, Hostname用
bg_path     = '#9ACD32'  # ディレクトリ用
bg_git      = '#2e2930'  # Git用
bg_host     = '#C1C1FF'
fg_main     = '#fbf1c7'  # 明るいクリーム色の文字
fg_dark     = '#1d2021'
fg_git      = '#5EA4EB'
color_red   = '#fb4934'  # エラー・警告用
color_green = '#b8bb26'  # 成功シンボル用
color_blue  = '#83a598'  # Vimモード用

[os]
disabled = false
style = "bg:bg_dark fg:fg_main"
format = "[ $symbol ]($style)"

[os.symbols]
Windows = "Win"
Ubuntu = "Ubu"
SUSE = "SUS"
Mint = "Min"
Macos = "Mac"
Manjaro = "Man"
Fedora = "Fed"
AlmaLinux = "Alm"
Amazon = "Amz"
Android = "And"
Arch = "Arc"
CentOS = "Cen"
Debian = "Deb"
Redhat = "Rhl"

[username]
show_always = true
style_user = "bg:bg_dark fg:fg_main"
style_root = "bg:color_red fg:fg_main"
format = "[ $user ]($style)"

[directory]
truncation_length = 3
style = "bg:bg_path fg:fg_dark bold"
format = "[ $path ]($style)"
read_only = " [RO]"
read_only_style = "bg:bg_path fg:color_red"

[git_branch]
symbol = "git:"
style = "bg:bg_git fg:fg_git bold"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:bg_git fg:fg_git"
up_to_date = ""
format = "[($all_status$ahead_behind )]($style)"

[fill]
symbol = " "

[hostname]
ssh_only = false
style = "bg:bg_host fg:fg_dark bold"
format = "[ $hostname ]($style)"

[character]
success_symbol = "[>>>](bold color_green)"
error_symbol = "[>>>](bold color_red)"
vimcmd_symbol = "[<<<](bold color_blue)"

