"$schema" = 'https://starship.rs/config-schema.json'

#############################################################################################

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$fill\
$hostname\
$line_break$character
"""

#############################################################################################

palette = 'color'

[palettes.color]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

#############################################################################################

[os]
disabled = false
style = "fg:#000000 bg:#f1f1f1"
format = """
[░▒▓](#f1f1f1)\
[$symbol]($style)\
"""

[os.symbols]
Windows = "󰖳 "
Ubuntu = "󰕈 "
SUSE = " "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Fedora = "󰣛 "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " 󰣇 "
EndeavourOS = " "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Pop = " "

#############################################################################################

[username]
style_user = "bold fg:#000000 bg:#f1f1f1"
style_root = "bold fg:#000000 bg:#ff7f7f"
format = '[ $user ]($style)'

#############################################################################################

[directory]
truncation_length = 10
truncation_symbol = "  …/"
truncate_to_repo = false
home_symbol = '  ~'
read_only = '󰌾 '
style = "bold fg:#000000 bg:#99ff33"
read_only_style = "fg:#000000 bg:#99ff33"
use_logical_path = false
format = """
[](fg:#99ff33 bg:#f1f1f1)\
[ $read_only]($read_only_style)\
[$path ]($style)\
[](fg:#99ff33 bg:none)\
"""

#############################################################################################

[git_branch]
symbol = "    "
truncation_length = 20
truncation_symbol = ""
style = "bold fg:#89dceb bg:#45475a"
format = """
[](fg:#45475a bg:none)\
[$symbol$branch(:$remote_branch) ]($style)\
"""

[git_status]
style = 'bold fg:#eba0ac bg:#45475a'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = '$'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = """
[ 󱪙 ](fg:#89dceb bg:#45475a)\
[$all_status$ahead_behind ]($style)\
[](fg:#45475a bg:none)\
"""

#############################################################################################

[fill]
symbol = " "
style = "fg:#3f3f3f bg:none"

#############################################################################################

[hostname]
style = "bold fg:#000000 bg:#bcbcff"
format = """
[](fg:#bcbcff bg:none)\
[ $hostname ]($style)\
[▓▒░](fg:#bcbcff bg:none)\
"""

#############################################################################################

[character]
success_symbol = "[❯](bold #99ff33)[❯](bold #33ff33)[❯](bold #00cc33)"
error_symbol = "[❯](bold #89dceb)[❯](bold #f38ba8)[❯](bold #f17497)"
vimcmd_symbol = "[❮](bold #99ff33)[❮](bold #33ff33)[❮](bold #00cc33)"
